# Generated by Django 4.0.3 on 2022-04-03 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5)),
                ('course_number', models.IntegerField(blank=True, null=True)),
                ('instructor_name', models.CharField(max_length=30)),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
            ],
        ),
    ]
