# Generated by Django 4.0.3 on 2022-04-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='course_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='instructor_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
